[package]
name = "di-container"
version = "0.2.0"
edition = "2024"
description = "Simple dependency injection container for Rust with derive macro support"
license = "MIT"
repository = "https://github.com/paulpeters144/di-container"
readme = "README.md"
keywords = ["dependency-injection", "di", "container", "injectable", "ioc"]
categories = ["rust-patterns"]

[dependencies]
di-container-derive = { version = "=0.2.0", path = "derive" }

[dev-dependencies]
pollster = "0"
