[package]
name = "di-container-derive"
version = "0.2.0"
edition = "2024"
description = "Derive macro for di-container dependency injection"
license = "MIT"
repository = "https://github.com/paulpeters144/di-container"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "=1.0.107"
quote = "=1.0.47"
syn = { version = "=2.0.119", features = ["full"] }
